# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "078842956c2220c00f9bfacccc278047"
application_url = "https://dept-debate-intervals-trap.trycloudflare.com"
embedded = true
name = "kfo-dev"
handle = "kfo-dev"

[build]
include_config_on_deploy = true
dev_store_url = "profill-dev.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_checkouts,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_products,read_returns,read_shipping,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_checkouts,write_customers,write_discounts,write_draft_orders,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_products,write_returns,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://dept-debate-intervals-trap.trycloudflare.com/auth/callback",
  "https://dept-debate-intervals-trap.trycloudflare.com/auth/shopify/callback",
  "https://dept-debate-intervals-trap.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
